---
title: "MP4"
author: "Sam Ellinwood, Haley McAtee, Sam Schneider"
date: "11/28/2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(mdsr)
library(tidyverse)
library(RMySQL)
```

```{r}
db <- dbConnect_scidb(dbname = "imdb")
tbl_1 <- db %>%
  dbGetQuery("SELECT DISTINCT t1.movie_id, t1.title, t1.production_year, t2.movie_id
FROM (SELECT DISTINCT aka_title.movie_id, title, production_year FROM aka_title) AS t1
JOIN (SELECT DISTINCT movie_keyword.movie_id FROM movie_keyword JOIN imdb.keyword ON keyword.id = movie_keyword.keyword_id 
	WHERE keyword.id = 1149 OR keyword.id = 4232
	OR keyword.id = 4671 OR keyword.id = 4672 OR keyword.id = 4669) AS t2
ON t1.movie_id = t2.movie_id;")
```

```{r}
tbl_2 <- db %>%
  dbGetQuery("SELECT DISTINCT movie_id, production_year
             FROM aka_title") %>%
  group_by(production_year) %>%
  summarize("total_num_movies" = n())
```

```{r}
tbl_3 <- tbl_1[!duplicated(tbl_1$movie_id), (colnames(tbl_1))] %>%
  left_join(tbl_2, by = "production_year")
```


```{r}
tbl_3 %>%
  filter(production_year > 1937, production_year < 2017) %>%
  group_by(production_year) %>%
  summarize("num_terror_movies" = n(),
            "total_num_movies" = mean(total_num_movies),
            "num_terror_controlled" = num_terror_movies/total_num_movies)  %>%
  ggplot(aes(x = production_year, y = num_terror_controlled)) + 
  geom_line() +
  scale_x_continuous(breaks=seq(1900,2017,20)) +
  ggtitle("Percentage of Movies Tagged as 'Terrorist' from 1937-2017") +
  labs(x="Year",y="Percentage of Movies") +
  scale_y_continuous(labels = scales::percent) + 
    annotate("point", shape = 21, x = 2001, y = .0063, color = "black", fill = "red", size = 5) +
  annotate("segment", shape = 21, x = 2001, xend = 2001, y = .006, yend = .0033, color = "red") +
  annotate("text", color = "black", label = "9/11 Attack", x = 2001, y = .003) +
  annotate("point", shape = 21, x = 1995, y = .0066, color = "black", fill = "red", size = 5) +
  annotate("segment", shape = 21, x = 1995, xend = 1995, y = .0062, yend = .0041, color = "red") +
  annotate("text", color = "black", label = "OKC Bombing", x = 1992, y = .004) +
  annotate("point", shape = 21, x = 1970, y = .0023, color = "black", fill = "red", size = 5) +
  annotate("segment", shape = 21, x = 1970, xend = 1970, y = .0025, yend = .0068, color = "red") +
  annotate("text", color = "black", label = "Beginning of", x = 1970, y = .0088) +
  annotate("text", color = "black", label = "'Golden Age'", x = 1970, y = .008) +
  annotate("text", color = "black", label = "of Terrorism", x = 1970, y = .0072)
```

